#!/bin/bash

# Parse command-line arguments
for arg in "$@"; do
    case "$arg" in
        --perf)
            export MUST_GATHER_PERF=true
            ;;
    esac
done

# generate /must-gather/version file
. version
echo "openshift/must-gather" >/must-gather/version
version >>/must-gather/version

source $(dirname "$0")/common.sh
source $(dirname "$0")/perf_utils.sh
get_log_collection_args

# Initialise performance tracking
perf_init
perf_start_monitor

# Store PIDs of all the subprocesses
pids=()

# Named resource list, eg. ns/openshift-config
named_resources=()

# Resource groups list, eg. pods
group_resources=()

# Resources to gather with `--all-namespaces` option
all_ns_resources=()

# Cluster Version Information
named_resources+=(ns/openshift-cluster-version)
group_resources+=(clusterversion)

# Operator and APIService Resources
group_resources+=(clusteroperators apiservices)

# Certificate Resources
group_resources+=(certificatesigningrequests)

# Machine/Node Resources
group_resources+=(nodes)

# Namespaces/Project Resources
named_resources+=(ns/default ns/openshift ns/kube-system ns/openshift-etcd)

# Storage Resources
group_resources+=(storageclasses persistentvolumes volumeattachments csidrivers csinodes volumesnapshotclasses volumesnapshotcontents volumegroupsnapshotclasses volumegroupsnapshotcontents clustercsidrivers volumeattributesclasses)
all_ns_resources+=(csistoragecapacities)

# Image-source Resources
group_resources+=(imagecontentsourcepolicies.operator.openshift.io)

# Networking Resources
group_resources+=(networks.operator.openshift.io)

# NodeNetworkState
resources+=(nodenetworkstates nodenetworkconfigurationenactments nodenetworkconfigurationpolicies)

# Assisted Installer
named_resources+=(ns/assisted-installer)

# Leases
all_ns_resources+=(leases)

# Flowcontrol - API Priority and Fairness (APF)
group_resources+=(prioritylevelconfigurations.flowcontrol.apiserver.k8s.io flowschemas.flowcontrol.apiserver.k8s.io)

# ClusterResourceQuota
group_resources+=(clusterresourcequotas.quota.openshift.io)

# Run the Collection of Resources using inspect
# running across all-namespaces for the few "Autoscaler" resources.
oc adm inspect ${log_collection_args} --dest-dir must-gather --rotated-pod-logs "${named_resources[@]}" &
pids+=($!)
perf_track_pid "oc_adm_inspect_named" "$!"

filtered_group_resources=()
for gr in "${group_resources[@]}"; do
	oc get "$gr" >/dev/null 2>&1
	if [[ "$?" -eq 0 ]]; then
		filtered_group_resources+=("$gr")
	fi
done
group_resources_text=$(
	IFS=,
	echo "${filtered_group_resources[*]}"
)
oc adm inspect ${log_collection_args} --dest-dir must-gather --rotated-pod-logs "${group_resources_text}" &
pids+=($!)
perf_track_pid "oc_adm_inspect_group" "$!"

all_ns_resources_text=$(
	IFS=,
	echo "${all_ns_resources[*]}"
)
oc adm inspect ${log_collection_args} --dest-dir must-gather --rotated-pod-logs "${all_ns_resources_text}" --all-namespaces &
pids+=($!)
perf_track_pid "oc_adm_inspect_all_ns" "$!"

# Gather Insights Operator Archives
perf_track_script "gather_insights" /usr/bin/gather_insights &
pids+=($!)

# Gather monitoring data from the cluster
perf_track_script "gather_monitoring" /usr/bin/gather_monitoring &
pids+=($!)

# Gather optional operator resources from all namespaces
perf_track_script "gather_olm" /usr/bin/gather_olm &
pids+=($!)

# Gather OLM v1 resources
perf_track_script "gather_olm_v1" /usr/bin/gather_olm_v1 &
pids+=($!)

# Gather API Priority and Fairness Endpoints
perf_track_script "gather_priority_and_fairness" /usr/bin/gather_priority_and_fairness &
pids+=($!)

# Gather etcd information
perf_track_script "gather_etcd" /usr/bin/gather_etcd &
pids+=($!)

# Gather Service Logs (using a supplemental Script); Scoped to Masters.
perf_track_script "gather_service_logs" /usr/bin/gather_service_logs master &
pids+=($!)

# Gather Windows Kubernetes component logs
perf_track_script "gather_windows_node_logs" /usr/bin/gather_windows_node_logs &
pids+=($!)

# Gather HAProxy config files
perf_track_script "gather_haproxy_config" /usr/bin/gather_haproxy_config &
pids+=($!)

# Gather kas startup and termination logs
perf_track_script "gather_kas_startup_termination_logs" /usr/bin/gather_kas_startup_termination_logs &
pids+=($!)

# Gather network logs
perf_track_script "gather_network_logs_basics" /usr/bin/gather_network_logs_basics &
pids+=($!)

# Gather metallb logs
perf_track_script "gather_metallb" /usr/bin/gather_metallb &
pids+=($!)

# Gather frr-k8s logs
perf_track_script "gather_frrk8s" /usr/bin/gather_frrk8s &
pids+=($!)

# Gather NMState
perf_track_script "gather_nmstate" /usr/bin/gather_nmstate &
pids+=($!)

# Gather Node Feature Discovery (NFD)
/usr/bin/gather_nfd &
pids+=($!)

# Gather SR-IOV resources
perf_track_script "gather_sriov" /usr/bin/gather_sriov &
pids+=($!)

# Gather PodNetworkConnectivityCheck
perf_track_script "gather_podnetworkconnectivitycheck" /usr/bin/gather_podnetworkconnectivitycheck &
pids+=($!)

# Gather On-Disk MachineConfig files
perf_track_script "gather_machineconfig_ondisk" /usr/bin/gather_machineconfig_ondisk &
pids+=($!)

# Gather On-Disk MachineConfigDaemon logs
perf_track_script "gather_machineconfigdaemon_termination_logs" /usr/bin/gather_machineconfigdaemon_termination_logs &
pids+=($!)

# Gather vSphere resources. This is NOOP on non-vSphere platform.
perf_track_script "gather_vsphere" /usr/bin/gather_vsphere &
pids+=($!)

# Gather Performance profile information
perf_track_script "gather_ppc" /usr/bin/gather_ppc &
pids+=($!)

# Gather OSUS information
perf_track_script "gather_osus" /usr/bin/gather_osus &
pids+=($!)

# Gather Istio/Gateway API information
perf_track_script "gather_istio" /usr/bin/gather_istio &
pids+=($!)

# Check if PID array has any values, if so, wait for them to finish
if [ ${#pids[@]} -ne 0 ]; then
	echo "Waiting on subprocesses to finish execution."
	wait "${pids[@]}"
fi

# Gather ARO information
perf_track_script "gather_aro" /usr/bin/gather_aro

# Stop resource monitor and generate the performance report
perf_stop_monitor
perf_generate_report

# force disk flush to ensure that all data gathered is accessible in the copy container
sync
